### ISSUE TITLE
Readme is not understandable

### ISSUE THREAD

**Issue by jdittrich** [wmde/DataValuesJavaScript#130]
**Story:** As a programmer (also one internal to the org) I want to understand what this javascript package does.

**Problem:** 
> It contains various JavaScript related to the DataValues library.

Does not tell anything about what it does and how it could be used . 

**Suggestion:** 

* Provide context: *This can be used with [other code/product]  for [goal]*
* Provide reason: *We created this to [goal]*
* Provide use: *If you want to use the library…*
* Provide coding standards: *We follow… please use the .jshint file in the … folder.*

**Helpful:**

*  [writing better readmes](https://opensource.com/open-organization/17/10/readme-maturity-model)

**Comment by thiemowmde** [comment]
@jdittrich, can this be considered done with 94beb5eaa9dd1c266c9ea40fcc60c76320acd905?

**Comment by jdittrich** [comment]
yes, fine so far.

**Comment by ricordisamoa** [comment]
If you'd like the project description to be useful also to those who are not familiar with Wikibase, then better include or link to an explanation of what "DataValue" is :wink:

**Comment by thiemowmde** [comment]
"DataValue" is an interface. [Here is the PHP version](https://github.com/DataValues/DataValues/blob/master/src/DataValues/DataValue.php), and [here is the JavaScript one](https://github.com/wmde/DataValuesJavaScript/blob/master/src/DataValue.js). I hoped this became more obvious with what I did in 94beb5eaa9dd1c266c9ea40fcc60c76320acd905. Feel free to suggest other wordings.

Note that quite some of the public methods in the PHP interface are not used any more, most notably the getSortKey method.

**Comment by ricordisamoa** [comment]
I don't know. As the library seems to be mostly intended for internal use, it may be actually fine to need a more in-depth knowledge of Wikibase in order to understand what it does in practice.
