### ISSUE TITLE
please fix the readme

### ISSUE THREAD

**Issue by Echological** [wmde/DataValuesJavaScript#142]
this is intentionally a really shitty issue
but the readme is shitty.
nobody cares about a changelog as the readme
give us actual information about how to use this and stuff like that
then maybe move the changelog to a different file or smth idk
just make it easier to understand

**Comment by manicki** [comment]
Hello, it would interesting to understand what brought you to this library/this repository in the first place, and what information you are actually missing.
The library is primarily for WMDE's internal usage. While the README is not ideal, knowing what people are trying to make with it might help us better support them (e.g. by providing more information in the said README file).

**Comment by Echological** [comment]
it was on npm, and came up to a search of mine, and it looked useful but i did not actually know what it did.

my only concern was that, since it was on npm publicly, that it was a public package and it was difficult to understand.
