### ISSUE TITLE
Rename repo from DataValuesJavascript to DataValuesJavaScript

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/DataValuesJavaScript#65]
As suggested in #63

**Comment by JeroenDeDauw** [comment]
@snaterlicious @adrianheine @tobijat Anyone see a problem with doing such a rename?

(Note: GitHub creates a redirect, so you can continue pushing to, and pulling from, the old URL)

**Comment by adrianheine** [comment]
I'm in favor of that.

**Comment by JeroenDeDauw** [comment]
I'll rename this weekend if no one posted concerns by then

**Comment by addshore** [comment]
Well, this never happened ;)
